### PR TITLE
Update/upstream

### PR DESCRIPTION
**Pull request by jwgoh**
https://github.com/zurb/inky/pull/45 Updating upstream to support adding atrributes to outputted html (mainly for `valign`)

### CODE REVIEW

**Review by tikal — COMMENTED** [review]
@jwgoh was there no other alternative here ? @kainanaina 
Rather avoid touching dependencies too much... But I have a limited knowledge of the requirement here.

**Comment by jwgoh** [comment]
The alternative is to change the design i.e. caption above the images (so we don't have to bottom align the images). Since inky supports [vertical alignment](https://foundation.zurb.com/emails/docs/alignment.html#vertical-alignment) I was like great (but we need to update upstream)!

I think updating dependencies is something that we need to do. But yes, without adequate testing this might break a lot of things

**Comment by tikal** [comment]
@jwgoh I would like us to do "adequate testing" then :)

**Comment by jwgoh** [comment]
Closing in favour of https://github.com/nugit/inky/pull/2

**Pull request closed without merging**
